version: '3.4'

services:
  TestTaskService.Api:
    image: ${DOCKER_REGISTRY-}taskdexapi
    build:
      context: .
      dockerfile: src/Services/TestTaskService/TestTaskService.Api/TestTaskService.Api/Dockerfile
